#!/usr/bin/env python3
# proto_radar_lever.py - FALSIFIABLE prototype: recover a translation-only (Doppler radar) sensor's
# LEVER ARM from real nuScenes radar data using ONLY the linear hand-eye TRANSLATION row, which never
# needs the source's own rotation. De-risks the planned "translation-only-source lever estimator"
# core feature BEFORE it is built (Python tools/ prototype only; NO C++/core, NO doc edits).
#
# THE CLAIM UNDER TEST -----------------------------------------------------------------------------
#   A Doppler radar reports a per-window sensor-frame displacement t_B (which PHYSICALLY contains the
#   lever term, v_sensor = v_ego + omega x lever) but NO rotation (R_B = I, heading-blind). Its lever
#   t_X is recoverable from the hand-eye translation identity  A X = X B  with X = (R_X, t_X):
#
#       (R_A - I) t_X = R_X t_B - t_A
#
#   It needs only the BASE rotation R_A + base translation t_A (here from GT ego_pose) + the KNOWN
#   mount rotation R_X (from the trusted prior) + the source translation t_B. It NEVER uses the radar's
#   own (absent) rotation. Accumulate over many TURN windows -> 3x3 normal equations -> solve t_X.
#   On planar (yaw-only) driving (R_A - I) has the z-axis in its null space -> the z-lever is
#   UNOBSERVABLE but x,y ARE observable. Success target: radar x,y lever within a few cm; z at prior.
#
# DATA: the per-scene radar increment + GT CSVs in nuscenes_run/_per_scene/ (generated by
#   nuscenes_to_csv.py via nuscenes_concat.py --keep-temp). The TRUE mounts (R_X, t_X) are the
#   prior_extrinsic lines in nuscenes_run/mini_concat.ini (yaw pitch roll x y z, radians/m).
#   Multiple scenes give the turn excitation that one 20 s scene lacks.
#
# FALSIFICATION PROBES (mandatory; designed so it CAN fail):
#   (a) WRONG R_X (true mount yaw perturbed +20 deg) -> lever recovery must DEGRADE (proves R_X is the
#       load-bearing trusted input: supply it from the prior, do NOT recover it from a heading-blind source).
#   (b) z stays UNOBSERVABLE on planar driving (tiny N eigenvalue) and the solve leaves z near prior.
#   (c) ACCUMULATION: one short scene under-determines x,y (high condition number); many scenes resolve them.
#   (d) SANITY: the wheel reference (lever ~0) recovers ~0.
#
# Pure ASCII; numpy only; deterministic (no RNG needed -- the radar RANSAC seeding lives upstream).
#
# Usage:
#   python tools/proto_radar_lever.py [run_dir] [--win-s S] [--gate G] [--ridge R] [--base gt|consensus]
#   defaults: run_dir=nuscenes_run, win-s=1.0, gate=0.05 rad, ridge=1e-3, base=gt
import math
import os
import sys

import numpy as np

# ----- the 10 v1.0-mini scenes (per_scene file basenames) -----
ALL_SCENES = ["scene-0061", "scene-0103", "scene-0553", "scene-0655", "scene-0757",
              "scene-0796", "scene-0916", "scene-1077", "scene-1094", "scene-1100"]
RADARS = ["radar_front", "radar_front_left", "radar_front_right",
          "radar_back_left", "radar_back_right"]


# ---------------- linear algebra helpers (w-first quaternions, mirror the existing protos) -------
def quat_to_R(qw, qx, qy, qz):
    n = math.sqrt(qw * qw + qx * qx + qy * qy + qz * qz) or 1.0
    qw, qx, qy, qz = qw / n, qx / n, qy / n, qz / n
    return np.array([[1 - 2 * (qy * qy + qz * qz), 2 * (qx * qy - qz * qw), 2 * (qx * qz + qy * qw)],
                     [2 * (qx * qy + qz * qw), 1 - 2 * (qx * qx + qz * qz), 2 * (qy * qz - qx * qw)],
                     [2 * (qx * qz - qy * qw), 2 * (qy * qz + qx * qw), 1 - 2 * (qx * qx + qy * qy)]])


def so3_log(R):
    c = max(-1.0, min(1.0, (np.trace(R) - 1) / 2.0))
    th = math.acos(c)
    if th < 1e-12:
        return np.zeros(3)
    return np.array([R[2, 1] - R[1, 2], R[0, 2] - R[2, 0], R[1, 0] - R[0, 1]]) * (th / (2 * math.sin(th)))


def Rz(a):
    c, s = math.cos(a), math.sin(a)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])


def Ry(a):
    c, s = math.cos(a), math.sin(a)
    return np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]])


def Rx(a):
    c, s = math.cos(a), math.sin(a)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]])


def euler_to_R(yaw, pitch, roll):  # Rz(yaw)Ry(pitch)Rx(roll) -- the config_loader convention
    return Rz(yaw) @ Ry(pitch) @ Rx(roll)


# ---------------- CSV loaders ----------------
def load_increments(path):
    # increment CSV: t_ns, x,y,z, qw,qx,qy,qz, 6var. Return list of (t_ns, t(3), R(3x3)).
    out = []
    with open(path) as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            v = s.split(",")
            t_ns = int(v[0])
            t = np.array([float(v[1]), float(v[2]), float(v[3])])
            R = quat_to_R(float(v[4]), float(v[5]), float(v[6]), float(v[7]))
            out.append((t_ns, t, R))
    return out


def load_gt(path):
    # absolute GT poses: t_ns, x,y,z, qw..qz. Return (ts[np], pos[Nx3], Rs[list of 3x3]).
    ts, pos, Rs = [], [], []
    with open(path) as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            v = s.split(",")
            ts.append(int(v[0]))
            pos.append([float(v[1]), float(v[2]), float(v[3])])
            Rs.append(quat_to_R(float(v[4]), float(v[5]), float(v[6]), float(v[7])))
    return np.array(ts, dtype=np.int64), np.array(pos), Rs


def parse_priors(ini_path):
    # Return {short: (R_X(3x3), t_X(3), (yaw,pitch,roll))} from prior_extrinsic lines.
    priors = {}
    cur_csv = None
    with open(ini_path) as f:
        for line in f:
            s = line.strip()
            if s.startswith("csv ="):
                cur_csv = s.split("=", 1)[1].strip()
            elif s.startswith("prior_extrinsic ="):
                vals = [float(x) for x in s.split("=", 1)[1].split()]
                yaw, pitch, roll, lx, ly, lz = vals
                # csv name like mini_concat_radar_front.csv -> radar_front
                base = os.path.basename(cur_csv)[:-4]
                idx = base.find("radar_")
                short = base[idx:] if idx >= 0 else base
                priors[short] = (euler_to_R(yaw, pitch, roll),
                                 np.array([lx, ly, lz]), (yaw, pitch, roll))
    return priors


# ---------------- GT pose interpolation within a scene ----------------
def gt_pose_at(ts, pos, Rs, t_query):
    # Linear-interp position; nearest-pose rotation (windows are >=1 s so rotation interp error is
    # negligible vs the >0.05 rad turn gate; nearest keeps it simple and robust). Returns (R, p).
    i = int(np.searchsorted(ts, t_query))
    if i <= 0:
        return Rs[0], pos[0]
    if i >= len(ts):
        return Rs[-1], pos[-1]
    t0, t1 = ts[i - 1], ts[i]
    a = 0.0 if t1 == t0 else (t_query - t0) / float(t1 - t0)
    p = pos[i - 1] * (1 - a) + pos[i] * a
    R = Rs[i - 1] if a < 0.5 else Rs[i]
    return R, p


def base_delta_gt(ts, pos, Rs, t0, t1):
    # Base delta over [t0,t1] in the t0-ego frame:
    #   R_A = R0^T R1 ;  t_A = R0^T (p1 - p0)
    R0, p0 = gt_pose_at(ts, pos, Rs, t0)
    R1, p1 = gt_pose_at(ts, pos, Rs, t1)
    R_A = R0.T @ R1
    t_A = R0.T @ (p1 - p0)
    return R_A, t_A


def base_delta_consensus(inc, t0, t1):
    # Base delta over [t0,t1] by integrating a source's own increments (wheel or imu consensus).
    # inc = list of (t_ns, t(3), R(3x3)) increments. Accumulate increments with t_ns in (t0, t1].
    R = np.eye(3)
    p = np.zeros(3)
    for (t_ns, td, Rd) in inc:
        if t_ns <= t0 or t_ns > t1:
            continue
        p = R @ td + p
        R = R @ Rd
    return R, p


# ---------------- window builder: sum radar increments per [t0,t1] tile, pair with base delta -----
def build_windows(radar_inc, base_fn, win_ns, gate, scene_span_ns):
    # Tile the scene into [t0, t0+win_ns) windows. For each: sum radar increments (R_B ~ I so the
    # sensor-frame displacement is the running R-rotated sum, but since R stays ~I we sum directly),
    # get the base delta, gate on ||log R_A|| > gate. Return list of (R_A, t_A, t_B, logRA_norm).
    wins = []
    t0 = 0
    # index radar increments for fast windowing
    idx = 0
    n = len(radar_inc)
    while t0 < scene_span_ns:
        t1 = t0 + win_ns
        # sum radar sensor-frame displacement over the window. R_B accumulates too (should stay ~I).
        Rb = np.eye(3)
        tb = np.zeros(3)
        any_row = False
        for (t_ns, td, Rd) in radar_inc:
            if t_ns <= t0 or t_ns > t1:
                continue
            tb = Rb @ td + tb
            Rb = Rb @ Rd
            any_row = True
        if any_row:
            R_A, t_A = base_fn(t0, t1)
            nrm = float(np.linalg.norm(so3_log(R_A)))
            if nrm > gate:
                wins.append((R_A, t_A, tb, nrm))
        t0 = t1
    return wins


def solve_lever(wins, R_X, t_prior, ridge):
    # Accumulate N = sum (R_A - I)^T (R_A - I), g = sum (R_A - I)^T (R_X t_B - t_A).
    # Solve t_X = (N + ridge*tr(N)/3 * I) \ (g + ridge*tr(N)/3 * t_prior)  (ridge toward the prior).
    N = np.zeros((3, 3))
    g = np.zeros(3)
    for (R_A, t_A, t_B, _nrm) in wins:
        M = R_A - np.eye(3)
        rhs = R_X @ t_B - t_A
        N += M.T @ M
        g += M.T @ rhs
    ev = np.linalg.eigvalsh(N)  # ascending; per-axis observability
    lam = ridge * (np.trace(N) / 3.0 if np.trace(N) > 0 else 1.0)
    t_X = np.linalg.solve(N + lam * np.eye(3), g + lam * t_prior)
    return t_X, ev, N


def solve_lever_scale(wins, R_X, t_prior, ridge):
    # JOINT lever + Doppler scale (mirrors proto_lever_scale): unknowns u = [t_X; kappa], kappa = 1/scale
    #   (R_A - I) t_X - kappa (R_X t_B) = -t_A
    # The radar Doppler has a per-stream scale error; folding it in absorbs the dominant along-track
    # systematic instead of letting it leak into the x-lever. Returns (t_X, scale, ev4).
    AtA = np.zeros((4, 4))
    Atb = np.zeros(4)
    for (R_A, t_A, t_B, _nrm) in wins:
        J = np.hstack([R_A - np.eye(3), (-(R_X @ t_B)).reshape(3, 1)])
        AtA += J.T @ J
        Atb += J.T @ (-t_A)
    ev = np.linalg.eigvalsh(AtA)
    lam = ridge * (np.trace(AtA) / 4.0 if np.trace(AtA) > 0 else 1.0)
    reg = lam * np.eye(4)
    breg = lam * np.array([t_prior[0], t_prior[1], t_prior[2], 1.0])  # ridge kappa toward 1 (scale 1)
    u = np.linalg.solve(AtA + reg, Atb + breg)
    scale = 1.0 / u[3] if abs(u[3]) > 1e-9 else float("inf")
    return u[:3], scale, ev


def synth_windows_from_gt(scene_dir, scenes, R_X, t_plant, win_ns, gate):
    # CONTROL: build IDEAL windows from GT only, synthesizing the perfect sensor displacement
    #   t_B = R_X^T [ t_A + (R_A - I) t_plant ]
    # so the only thing under test is the linear estimator's math/code (no real-sensor noise). A
    # correct estimator must recover t_plant to ~machine precision from these windows.
    wins = []
    for sc in scenes:
        gpath = os.path.join(scene_dir, "%s_gt.csv" % sc)
        if not os.path.exists(gpath):
            continue
        ts, pos, Rs = load_gt(gpath)
        span = ts[-1] if len(ts) else 0
        t0 = 0
        while t0 < span:
            t1 = t0 + win_ns
            R_A, t_A = base_delta_gt(ts, pos, Rs, t0, t1)
            nrm = float(np.linalg.norm(so3_log(R_A)))
            if nrm > gate:
                t_B = R_X.T @ (t_A + (R_A - np.eye(3)) @ t_plant)
                wins.append((R_A, t_A, t_B, nrm))
            t0 = t1
    return wins


# ---------------- per-radar evaluation over a set of scenes ----------------
def accumulate_wins(run_dir, scene_dir, scenes, radar, base_mode, win_ns, gate):
    # Build (and concatenate) turn windows for one radar across the given scenes. base_mode in
    # {gt, consensus}. Returns list of windows.
    all_wins = []
    for sc in scenes:
        rpath = os.path.join(scene_dir, "%s_%s.csv" % (sc, radar))
        if not os.path.exists(rpath):
            continue
        radar_inc = load_increments(rpath)
        span = radar_inc[-1][0] if radar_inc else 0
        if base_mode == "gt":
            ts, pos, Rs = load_gt(os.path.join(scene_dir, "%s_gt.csv" % sc))
            base_fn = lambda a, b, ts=ts, pos=pos, Rs=Rs: base_delta_gt(ts, pos, Rs, a, b)
        else:
            wheel = load_increments(os.path.join(scene_dir, "%s_wheel.csv" % sc))
            imu = load_increments(os.path.join(scene_dir, "%s_imu.csv" % sc))
            # consensus base = imu rotation (heading-grade) + imu translation; imu carries the heading
            base_fn = lambda a, b, imu=imu: base_delta_consensus(imu, a, b)
        all_wins += build_windows(radar_inc, base_fn, win_ns, gate, span)
    return all_wins


def main():
    args = sys.argv[1:]
    run_dir = "nuscenes_run"
    win_s = 1.0
    gate = 0.05
    ridge = 1e-3
    base_mode = "gt"
    pos_args = []
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--win-s":
            i += 1
            win_s = float(args[i])
        elif a == "--gate":
            i += 1
            gate = float(args[i])
        elif a == "--ridge":
            i += 1
            ridge = float(args[i])
        elif a == "--base":
            i += 1
            base_mode = args[i]
        else:
            pos_args.append(a)
        i += 1
    if pos_args:
        run_dir = pos_args[0]

    scene_dir = os.path.join(run_dir, "_per_scene")
    ini_path = os.path.join(run_dir, "mini_concat.ini")
    if not os.path.isdir(scene_dir):
        print("ERROR: %s not found (run nuscenes_concat.py --keep-temp first)" % scene_dir)
        sys.exit(1)
    priors = parse_priors(ini_path)
    win_ns = int(win_s * 1e9)
    scenes = [s for s in ALL_SCENES
              if os.path.exists(os.path.join(scene_dir, "%s_radar_front.csv" % s))]

    print("=" * 90)
    print("RADAR LEVER-ARM PROTOTYPE  (hand-eye translation row, source rotation NEVER used)")
    print("  (R_A - I) t_X = R_X t_B - t_A   accumulated over turn windows -> 3x3 normal eqs")
    print("=" * 90)
    print("run_dir=%s  scenes=%d  win=%.2fs  turn_gate=%.3f rad  ridge=%.1e  base=%s"
          % (run_dir, len(scenes), win_s, gate, ridge, base_mode))
    print()

    # ---------- (0) SYNTHETIC CONTROL: prove the estimator MATH/CODE is exact ----------
    # Plant a known lever, synthesize the IDEAL sensor displacement from GT, recover it. If the linear
    # estimator is correct, error == machine precision. This separates "is the math right" (yes) from
    # "does the REAL radar data carry the signal" (the open question, sections 1+).
    print("-" * 90)
    print("(0) SYNTHETIC CONTROL -- ideal t_B from GT (no sensor noise): math/code must be EXACT")
    print("-" * 90)
    print("%-18s | %-22s | %-22s | %10s" % ("radar (planted)", "recovered xyz (m)", "true xyz (m)", "xy err"))
    print("-" * 78)
    for radar in RADARS:
        if radar not in priors:
            continue
        R_X, t_true, eul = priors[radar]
        sw = synth_windows_from_gt(scene_dir, scenes, R_X, t_true, win_ns, gate)
        t_X, ev, N = solve_lever(sw, R_X, t_true, ridge)
        exy = math.hypot(t_X[0] - t_true[0], t_X[1] - t_true[1]) * 100.0
        print("%-18s | [%6.3f %6.3f %6.3f] | [%6.3f %6.3f %6.3f] | %.2e cm"
              % (radar, t_X[0], t_X[1], t_X[2], t_true[0], t_true[1], t_true[2], exy))
    print("  -> if these are ~1e-12 cm, the (R_A-I) t_X = R_X t_B - t_A estimator is provably correct;")
    print("     any real-data error below is sensor noise, NOT a math/code bug.")

    # ---------- (1) MAIN: per-radar recovered vs true lever, with TRUE R_X (real radar t_B) ----------
    print()
    print("-" * 90)
    print("(1) MAIN RESULT -- recovered lever vs TRUE lever (REAL radar, all %d scenes, TRUE R_X)" % len(scenes))
    print("-" * 90)
    hdr = ("%-18s | %4s | %-20s | %-20s | %6s %6s | %-16s | %6s %6s %4s"
           % ("radar", "#win", "recovered xyz (m)", "true xyz (m)", "exC", "eyC",
              "N eig z|x|y", "exJ", "eyJ", "scl"))
    print(hdr)
    print("-" * len(hdr))
    main_rows = {}
    for radar in RADARS:
        if radar not in priors:
            continue
        R_X, t_true, eul = priors[radar]
        wins = accumulate_wins(run_dir, scene_dir, scenes, radar, base_mode, win_ns, gate)
        if not wins:
            print("%-18s | no turn windows" % radar)
            continue
        t_X, ev, N = solve_lever(wins, R_X, t_true, ridge)
        t_Xj, scl, evj = solve_lever_scale(wins, R_X, t_true, ridge)
        errx = abs(t_X[0] - t_true[0]) * 100.0
        erry = abs(t_X[1] - t_true[1]) * 100.0
        errxj = abs(t_Xj[0] - t_true[0]) * 100.0
        erryj = abs(t_Xj[1] - t_true[1]) * 100.0
        main_rows[radar] = (t_X, t_true, ev, len(wins), errx, erry)
        print("%-18s | %4d | [%5.2f %5.2f %5.2f] | [%5.2f %5.2f %5.2f] | %6.1f %6.1f | %.2g|%.2g|%.2g | %6.1f %6.1f %.3f"
              % (radar, len(wins),
                 t_X[0], t_X[1], t_X[2], t_true[0], t_true[1], t_true[2],
                 errx, erry, ev[0], ev[1], ev[2], errxj, erryj, scl))
    print()
    print("  exC/eyC = plain 3-DOF lever xy error (cm); exJ/eyJ/scl = joint lever+Doppler-scale solve.")
    print("  z (smallest N eig) is UNOBSERVABLE on planar driving -> pinned at prior by the ridge.")

    # ---------- (2) PROBE (a): WRONG R_X (+20 deg yaw) degrades recovery ----------
    print()
    print("-" * 90)
    print("(2) PROBE (a) -- WRONG R_X (true mount yaw + 20 deg): recovery must DEGRADE")
    print("-" * 90)
    dyaw = math.radians(20.0)
    print("Run on the SYNTHETIC-CONTROL windows (clean) so the probe is not masked by along-track")
    print("drift: with ideal t_B, a wrong R_X is the ONLY error source -> recovery must blow up.")
    print("%-18s | %12s | %12s | %12s" % ("radar", "true-RX cm", "wrong-RX cm", "degradation"))
    print("-" * 60)
    for radar in RADARS:
        if radar not in priors:
            continue
        R_X, t_true, eul = priors[radar]
        sw = synth_windows_from_gt(scene_dir, scenes, R_X, t_true, win_ns, gate)
        R_X_wrong = Rz(dyaw) @ R_X  # +20 deg yaw on the trusted mount
        t_good, _, _ = solve_lever(sw, R_X, t_true, ridge)
        t_bad, _, _ = solve_lever(sw, R_X_wrong, t_true, ridge)
        e_good = math.hypot(t_good[0] - t_true[0], t_good[1] - t_true[1]) * 100.0
        e_bad = math.hypot(t_bad[0] - t_true[0], t_bad[1] - t_true[1]) * 100.0
        ratio = (e_bad / e_good) if e_good > 1e-6 else float("inf")
        print("%-18s | %12.4g | %12.2f | %12s"
              % (radar, e_good, e_bad, ("x%.3g" % ratio if ratio != float("inf") else "inf")))
    print("  true R_X -> ~0 cm; wrong R_X (+20 deg) -> meters. R_X-correctness is LOAD-BEARING:")
    print("  supply R_X from the trusted prior; do NOT try to recover it from a heading-blind source.")
    # also report the real-data version for honesty (already drift-saturated, so less diagnostic)
    print()
    print("  [real-data, for honesty -- x already drift-saturated so this probe is muddy here:]")
    for radar in RADARS:
        if radar not in main_rows:
            continue
        R_X, t_true, eul = priors[radar]
        wins = accumulate_wins(run_dir, scene_dir, scenes, radar, base_mode, win_ns, gate)
        R_X_wrong = Rz(dyaw) @ R_X
        t_good, _, _ = solve_lever(wins, R_X, t_true, ridge)
        t_bad, _, _ = solve_lever(wins, R_X_wrong, t_true, ridge)
        # report the LATERAL (y) error -- the channel that actually carries signal on real data
        ey_good = abs(t_good[1] - t_true[1]) * 100.0
        ey_bad = abs(t_bad[1] - t_true[1]) * 100.0
        print("    %-18s  y-err true-RX %6.1f cm -> wrong-RX %6.1f cm" % (radar, ey_good, ey_bad))

    # ---------- (3) PROBE (b): z unobservable -- already shown via eigvals above; restate ----------
    print()
    print("-" * 90)
    print("(3) PROBE (b) -- z-lever UNOBSERVABLE on planar driving")
    print("-" * 90)
    print("%-18s | %10s | %12s | %10s | %10s"
          % ("radar", "z eig", "x,y eig", "z recovered", "z prior"))
    print("-" * 64)
    for radar in RADARS:
        if radar not in main_rows:
            continue
        t_X, t_true, ev, _nw, _ex, _ey = main_rows[radar]
        print("%-18s | %10.3g | %5.3g,%5.3g | %10.4f | %10.4f"
              % (radar, ev[0], ev[1], ev[2], t_X[2], t_true[2]))
    print("  z eigenvalue ~%.0e smaller than x,y -> z null space; z stays pinned at prior by the ridge."
          % 1)

    # ---------- (4) PROBE (c): accumulation curve -- condition number vs #scenes ----------
    print()
    print("-" * 90)
    print("(4) PROBE (c) -- ACCUMULATION: condition number + xy error vs #scenes (radar_front)")
    print("-" * 90)
    radar = "radar_front"
    R_X, t_true, eul = priors[radar]
    print("%6s | %5s | %14s | %14s | %10s | %10s"
          % ("#scene", "#win", "xy obs eig", "z/xy cond", "errX cm", "errY cm"))
    print("-" * 72)
    for k in range(1, len(scenes) + 1):
        wins = accumulate_wins(run_dir, scene_dir, scenes[:k], radar, base_mode, win_ns, gate)
        if not wins:
            print("%6d | (no windows)" % k)
            continue
        t_X, ev, N = solve_lever(wins, R_X, t_true, ridge)
        # xy observability = the SMALLEST observable (x,y) eigenvalue -> grows as windows accumulate
        # (more excitation = better-determined x,y). z/xy cond = how deeply z sits in the null space.
        xy_obs = ev[1]
        zcond = ev[1] / ev[0] if ev[0] > 1e-12 else float("inf")
        errx = abs(t_X[0] - t_true[0]) * 100.0
        erry = abs(t_X[1] - t_true[1]) * 100.0
        print("%6d | %5d | %14.4g | %14.3g | %10.2f | %10.2f"
              % (k, len(wins), xy_obs, zcond, errx, erry))
    print("  xy obs eig GROWS with scenes (better conditioning); z/xy cond stays high (z null space).")
    print("  BUT errX does NOT shrink -> the x error is a SYSTEMATIC along-track bias, not averageable")
    print("  noise; accumulation fixes geometry/conditioning, NOT the radar's along-track drift.")

    # ---------- (5) PROBE (d): sanity -- wheel reference (lever ~0) recovers ~0 ----------
    print()
    print("-" * 90)
    print("(5) PROBE (d) -- SANITY: a zero-lever source must recover ~0")
    print("-" * 90)
    # Clean version: synthesize ideal t_B for a PLANTED zero lever (R_X = I) from GT -> the estimator
    # must return ~0 (it does not invent a lever out of nothing).
    sw0 = synth_windows_from_gt(scene_dir, scenes, np.eye(3), np.zeros(3), win_ns, gate)
    t_s0, _, _ = solve_lever(sw0, np.eye(3), np.zeros(3), ridge)
    print("synthetic zero-lever (ideal t_B, R_X=I): recovered [%7.4f %7.4f %7.4f] m  |xy|=%.2e cm"
          % (t_s0[0], t_s0[1], t_s0[2], math.hypot(t_s0[0], t_s0[1]) * 100.0))
    print("  -> clean control: a true-zero lever recovers ~machine-zero (no invented lever).")
    # Real wheel reference: lever ~0, but its crude 2 Hz speed+yaw odom (lateral hardcoded 0) disagrees
    # with GT by ~0.5 m/window -> it is a SECOND witness to the same noise wall, NOT a clean zero.
    zero_wins = []
    for sc in scenes:
        wpath = os.path.join(scene_dir, "%s_wheel.csv" % sc)
        if not os.path.exists(wpath):
            continue
        wheel_inc = load_increments(wpath)
        span = wheel_inc[-1][0] if wheel_inc else 0
        ts, pos, Rs = load_gt(os.path.join(scene_dir, "%s_gt.csv" % sc))
        base_fn = lambda a, b, ts=ts, pos=pos, Rs=Rs: base_delta_gt(ts, pos, Rs, a, b)
        zero_wins += build_windows(wheel_inc, base_fn, win_ns, gate, span)
    if zero_wins:
        t_X0, ev0, _ = solve_lever(zero_wins, np.eye(3), np.zeros(3), ridge)
        print("REAL wheel (ref, R_X=I, true lever [0,0,0]): recovered [%6.3f %6.3f %6.3f] m  |xy|=%.1f cm #win=%d"
              % (t_X0[0], t_X0[1], t_X0[2], math.hypot(t_X0[0], t_X0[1]) * 100.0, len(zero_wins)))
        print("  -> the real wheel does NOT recover 0: its own ~0.5 m/window DR disagreement with GT")
        print("     amplifies the same way the radar's does -> confirms the wall is per-window t_B noise,")
        print("     not a radar-specific defect (any crude-odom source hits it).")
    else:
        print("  (no wheel turn windows)")

    # ---------- (6) DIAGNOSTIC: window-length sweep -- exposes the along-track drift wall ----------
    print()
    print("-" * 90)
    print("(6) DIAGNOSTIC -- window-length sweep (radar_front): exposes the noise that bounds recovery")
    print("-" * 90)
    radar = "radar_front"
    R_X, t_true, eul = priors[radar]
    print("%6s | %5s | %10s | %10s | %14s"
          % ("win_s", "#win", "errX cm", "errY cm", "t_B resid m"))
    print("-" * 58)
    for ws in [0.5, 1.0, 2.0, 3.0]:
        wns = int(ws * 1e9)
        wins = accumulate_wins(run_dir, scene_dir, scenes, radar, base_mode, wns, gate)
        if not wins:
            print("%6.1f | (no windows)" % ws)
            continue
        t_X, ev, N = solve_lever(wins, R_X, t_true, ridge)
        # residual = real t_B disagreement with the true-lever prediction, per window (xy)
        resid = np.mean([np.linalg.norm((R_X @ tb - ta - (Ra - np.eye(3)) @ t_true)[:2])
                         for (Ra, ta, tb, _n) in wins])
        print("%6.1f | %5d | %10.2f | %10.2f | %14.3f"
              % (ws, len(wins), abs(t_X[0] - t_true[0]) * 100.0,
                 abs(t_X[1] - t_true[1]) * 100.0, resid))
    print("  errX GROWS with window length -> the radar's ALONG-TRACK Doppler displacement drifts;")
    print("  that drift (t_B resid) is the noise floor that buries the small turn-induced x-lever.")
    print("  errY (lateral) stays small -> the y-lever is the recoverable component on real data.")

    print()
    print("=" * 90)
    print("DONE. See REPORT for the verdict.")
    print("=" * 90)


if __name__ == "__main__":
    main()
